homeassistant:
  auth_providers:
   - type: command_line
     command: /home/homeassistant/.homeassistant/bin/ynh_ldap-auth.sh
     meta: true

http:
  server_port: __PORT__
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1
    - ::1

# Apply default set of integrations
default_config:
