title: Home
views:
  - path: default_view
    title: Home
    badges:
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - sensor.current_version
          - sensor.latest_available_version
          - switch.upgrade_homeassistant
        title: Home Assistant
